version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_DIALECT: sqlite
      DATABASE_STORAGE: /usr/src/app/database.sqlite
    volumes:
      - ./dist:/usr/src/app/dist

